- name: integration of terraform and ansible
  hosts: all
  gather_facts: 'no'

  tasks:
    - name: "Wait 300 seconds, but only start checking after 60 seconds"
      wait_for_connection:
        delay: 60
        timeout: 300

    - name: Configure general settings for the vyos hosts group
      vyos_config:
        lines:
          - set system name-server 8.8.8.8
        save:
          true
